if [ "$#" -lt 1 ]; then
    echo "Correct arguments: script" && exit 1
fi
BASE=TODO
KERNEL=TODO
DISTIMG=TODO

$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1 
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG   --l1u_size="2048B" --l1u_assoc=4 --caches --l2cache --cpu-type=DerivO3CPU  --checkpoint-dir=m5out -r 1  --no_ucache_protection; mv m5out/stats.txt m5out/stats2048B4assocfilteronly.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG   --l1u_size="2048B" --iucache --l1u_assoc=4 --nprefetch_spec --prefetch_ordered --caches --l2cache --cpu-type=DerivO3CPU   --checkpoint-dir=m5out -r 1  --meltdown --cache_coher; mv m5out/stats.txt m5out/statsmuontrap.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG   --l1u_size="2048B" --iucache --l1u_assoc=4 --nprefetch_spec --prefetch_ordered --caches --l2cache --cpu-type=DerivO3CPU   --checkpoint-dir=m5out -r 1  --meltdown --cache_coher; mv m5out/stats.txt m5out/statsclearmisspec.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --l1u_assoc=0 --caches --l2cache --cpu-type=DerivO3CPU  --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/statsno.txt

$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="64B" --l1u_assoc=1 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/stats64B.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="128B" --l1u_assoc=2 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/stats128B.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="256B" --l1u_assoc=4 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/stats256B.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="512B" --l1u_assoc=8 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/stats512B.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="1kB" --l1u_assoc=16 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/stats1kB.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="2kB" --l1u_assoc=32 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/stats2kB.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="4kB" --l1u_assoc=64 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/stats4kB.txt


$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="2048B" --l1u_assoc=1 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/stats2048B1assoc.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="2048B" --l1u_assoc=2 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/stats2048B2assoc.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="2048B" --l1u_assoc=4 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/stats2048B4assoc.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="2048B" --l1u_assoc=8 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/stats2048B8assoc.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="2048B" --l1u_assoc=16 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1; mv m5out/stats.txt m5out/stats2048B16assoc.txt

$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="2048B" --l1u_assoc=4 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1 --cache_coher; mv m5out/stats.txt m5out/stats2048B4assoccoher.txt
$BASE/gem5-spectre/build/ARM/gem5.opt $BASE/gem5-spectre/configs/example/fs.py --kernel=$KERNEL --machine-type=VExpress_GEM5_V1 --dtb-file=$BASE/gem5-spectre/system/arm/dt/armv8_gem5_v1_4cpu.dtb -n 4 --disk-image=$DISTIMG --script=$1  --l1u_size="2048B" --iucache --l1u_assoc=4 --caches --l2cache --cpu-type=O3_ARM_v7a_3 --checkpoint-dir=m5out -r 1 --cache_coher; mv m5out/stats.txt m5out/stats2048B4assoccoheriucache.txt
